= Asciidoctor.js PDF

ifdef::env-github[]
image:https://travis-ci.org/Mogztter/asciidoctor-pdf.js.svg?branch=master[Travis build status, link=https://travis-ci.org/Mogztter/asciidoctor-pdf.js]
endif::[]

Convert AsciiDoc document to PDF using Asciidoctor.js and Puppeteer (Headless Chrome)

== About

Inspired by an awesome project called https://github.com/RelaxedJS/ReLaXed/blob/master/src/index.js[Relaxed.JS].

Asciidoctor.js PDF is using Headless Chrome to generate a beautiful PDF.
It allows complex layouts to be defined with CSS and JavaScript, while writing the content in AsciiDoc.

== Examples

.Letter
 ./bin/asciidoctorjs-pdf ./examples/letter/letter.adoc --template-require ./examples/letter/template.js

.Book
 ./bin/asciidoctorjs-pdf ./examples/book/book.adoc --template-require ./examples/book/template.js

.Document
 ./bin/asciidoctorjs-pdf ./examples/document/document.adoc --template-require ./examples/document/templates/index.js

.slides
 ./bin/asciidoctorjs-pdf ./examples/slides/slides.adoc --template-require ./examples/slides/template.js
