////
Included in:

- user-manual: Macro and Block Passthroughs: Block passthroughs
////

The passthrough block and `pass` block style exclude block content from all substitutions (unless specified otherwise).

A passthrough block is delimited by four plus signs (`{plus}{plus}{plus}{plus}`).
The `pass` style is implied.

[source]
----
include::ex-pass.adoc[tag=bl]
----

(Keep in mind that AsciiDoc has a video macro, so this example is merely for demonstration.
However, a passthrough could come in handy if you need to output more sophisticated markup than what the built-in HTML converter produces).

The pass style can also be set on a paragraph or an open block.

[source]
----
include::ex-pass.adoc[tag=pass-style]
----

You can use the `subs` attribute to specify a comma-separated list of substitutions.
These substitutions will be applied to the content prior to it being reintroduced to the output document.

[source]
----
include::ex-pass.adoc[tag=subs-bl]
----

The content of the pass block does not get wrapped in a paragraph.
Therefore, you can use the `pass` style in combination with the `normal` substitution category to output content without generating a paragraph.

[source]
----
include::ex-pass.adoc[tag=no-para]
----
