////
Included in:

- user-manual: Quote
////

// tag::intro[]
Prose excerpts, quotes and verses share the same syntax structure, including:

* block name, either `quote` or `verse`
* name of who the content is attributed to
* bibliographical information of the book, speech, play, poem, etc., where the content was drawn from
* excerpt text
// end::intro[]

// tag::basic[]
For content that doesn't require the preservation of line breaks, set the `quote` attribute in the first position of the attribute list.
Next, set the attribution and relevant citation information.
However, these positional attributes are optional.

.Anatomy of a basic quote
----
[quote, attribution, citation title and information]
Quote or excerpt text
----

If the quote is a single line or paragraph, you can place the attribute list directly on top of the text.

.Quote paragraph syntax
[source]
----
include::ex-quote.adoc[tag=para2-c]
----
<1> Mark lead-in text explaining the context or setting of the quote using a period (`.`). (optional)
<2> For content that doesn't require the preservation of line breaks, set `quote` in the first position of the attribute list.
<3> The second position contains who the excerpt is attributed to. (optional)
<4> Enter additional citation information in the third position. (optional)
<5> Enter the excerpt or quote text on the line immediately following the attribute list.

.Result: Quote paragraph
====
include::ex-quote.adoc[tag=para2]
====

If the quote or excerpt is more than one paragraph, place the text between delimiter lines consisting of four underscores (`+____+`).

.Quote block syntax
[source]
----
include::ex-quote.adoc[tag=comp]
----

.Result: Quote block
====
include::ex-quote.adoc[tag=comp]
====

Asciidoctor also provides three alternative ways to markup quotes and prose excerpts.
// end::basic[]
