= Custom Styles

You can provide a custom stylesheet using the `stylesheet` attribute.
A custom stylesheet completely replaces the default stylesheet.

[source,sh]
----
asciidoctor-web-pdf document.adoc -a stylesheet="custom.css"
----

[TIP]
====
You can also provide a custom stylesheet *in addition* to all the default styles using the `+` prefix:

[source,sh]
----
asciidoctor-web-pdf document.adoc -a stylesheet="+custom.css"
----

Notice the `+` before `custom.css` — it means that the stylesheet will be included after all the default styles.
This is particularly useful when you want to override a few styles.
====

The `stylesheet` attribute can accept multiple comma-delimited values (without spaces).
This can be used to begin with a base stylesheet and then apply supplementary content:

[source,sh]
----
asciidoctor-web-pdf document.adoc -a stylesheet="custom.css,override.css"
----

It's also possible to use the default stylesheet and add custom styles with a custom stylesheet.
All default stylesheets are available under the prefix `asciidoctor-pdf/css/`:

[source,sh]
----
asciidoctor-web-pdf document.adoc -a stylesheet="asciidoctor-pdf/css/asciidoctor.css,asciidoctor-pdf/css/document.css,custom.css"
----

You can also specify where the stylesheets are located with the `stylesdir` attribute:

[source,sh]
----
asciidoctor-web-pdf document.adoc -a stylesdir=css -a stylesheet="custom.css,override.css"
----
