= Document Title
Doc Writer <doc@example.com>
:doctype: book
:reproducible:
:source-highlighter: highlight.js
:listing-caption: Listing

A simple http://asciidoc.org[AsciiDoc] document.

== Introduction

A paragraph followed by an unordered list{empty}footnote:[AsciiDoc supports unordered, ordered, and description lists.] with square bullets.footnote:[You may choose from square, disc, and circle for the bullet style.]

[square]
* item 1
* item 2

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!' // <1>
end
----
<1> Add `Hello, World!` as text

== Equations and Formulas

If you need to get technical in your writing, https://asciidoctor.org/docs/user-manual/#stem[Asciidoctor integrates with MathJax].

Here some examples:

:stem:

[example]
--
[stem]
++++
sqrt(4) = 2
++++

Water (stem:[H_2O]) is a critical component.
--

== Icons

:icons: font
//:icontype: svg

.Size & title
Do you want to drink a small icon:cocktail[sm] or a tall icon:beer[2x,title=pint] ?

.Fixed-width
icon:ruler-vertical[fw] vertical ruler +
icon:ruler-horizontal[fw] horizontal ruler

.Rotate
icon:flag[rotate=90] +
icon:flag[rotate=180] +
icon:flag[rotate=270] +
icon:flag[flip=horizontal] +
icon:flag[flip=vertical]

.Octicons
You can icon:repo-forked[set=octicons] me on icon:mark-github[set=octicons]... bip bip bop icon:hubot@octicons[]

.FontAwesome solid (default), regular and brand
icon:address-book[] icon:address-book[set=far] icon:chrome@fab[]

== Conclusion

That's all, folks!
