= Document Title
Doc Writer <doc@example.com>
:doctype: book
:toc:
:reproducible:
:source-highlighter: highlight.js
:listing-caption: Listing

A simple http://asciidoc.org[AsciiDoc] document.

== Introduction

A paragraph followed by an unordered list{empty}footnote:[AsciiDoc supports unordered, ordered, and description lists.] with square bullets.footnote:[You may choose from square, disc, and circle for the bullet style.]

[square]
* item 1
* item 2

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!' // <1>
end
----
<1> Add `Hello, World!` as text

== Equations and Formulas

If you need to get technical in your writing, https://asciidoctor.org/docs/user-manual/#stem[Asciidoctor integrates with MathJax].

Here some examples:

:stem:

[example]
--
[stem]
++++
sqrt(4) = 2
++++

Water (stem:[H_2O]) is a critical component.

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]
--

<<<

== Icons

:icons: font
//:icontype: svg

.Size & title
Do you want to drink a small icon:cocktail[sm] or a tall icon:beer[2x,title=pint] ?

.Fixed-width
icon:ruler-vertical[fw] vertical ruler +
icon:ruler-horizontal[fw] horizontal ruler

.Rotate
icon:flag[rotate=90] +
icon:flag[rotate=180] +
icon:flag[rotate=270] +
icon:flag[flip=horizontal] +
icon:flag[flip=vertical]

.Roles
icon:heart[role=is-primary] icon:heart[role=is-success] icon:heart[role=is-warning] icon:heart[role=is-danger]

.Set
icon:address-book[set=far] icon:address-book[] icon:chrome@fab[]

<<<

== Admonitions

CAUTION: Don't stick forks in electric sockets.

TIP: After someone sticks a fork in a socket, you'll need to reset the circuit in the breaker box in the dark and scary basement.

WARNING: Never go into the basement.

IMPORTANT: A monster lives in the basement.

NOTE: If you go into the basement, see if you can find Kenny's parka.

|===
|Header One | Header Two

| Cell 1
| Cell 2
|===

Definition Term::
Definition

[.text-left]
Text left

[.text-center]
Text center

[.text-right]
Text Right

[.text-justify]
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.
A big blob of text.

Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.
Stretch to the next page.

<<<

== Keep Together

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

a

=== Heading that should join paragraph on next page

b

== Conclusion

That's all, folks!
