== Apache Camel
// tag::update_2_1[]
Quarkus integrates wih https://camel.apache.org[Apache Camel].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-camel-core"
----

You can inject `CamelRuntime` and `CamelContext` instances:

[source, java]
----
@Inject
CamelRuntime runtime;
    
@Inject
CamelContext context;
----

And also observing Camel events `InitializingEvent`, `InitializedEvent`, `StartingEvent`, `StartedEvent`. `StoppingEvent`, `StoppedEvent`.

[source, java]
----
public void init(@Observes InitializingEvent event) {
    runtime.getContext()
            .setUuidGenerator(new DefaultUuidGenerator());
}
----

You can create `RouteBuilder` for routing rules:

[source, java]
----
public class CamelRoute extends RouteBuilder {

    @Override
    public void configure() {
        from("timer:keep-alive?" +
                "period={{camel.timer-route.period}}")
        .id("timer-route")
        .setBody(constant(""))
        .to("log:keep-alive");
    }
}
----

Custom properties are set in `application.properties`.

[source, properties]
----
camel.timer-route.period=1s
----

List of Camel parameters.

`quarkus.` as a prefix is skipped in the next table.

|===	
|Parameter | Default | Description

a|`camel.routesUris`
|
|Uri to an XML with camel routes.

a|`camel.deferInitPhase`
a|`false`
|Defer context initialization phase until runtime.

a|`camel.disableJaxb`
a|`false`
|Disable jaxb support at runtime. Useful when routes loaded at build time.

a|`camel.disableXml`
a|`false`
|Disable XML support in various parts of Camel.

a|`camel.dumpRoutes`
a|`false`
|Dump loaded routes .
|===

Quarkus also comes with support for Camel in form of next extensions: `camel-aws-s3`, `camel-aws-sqs`, `camel-infinispan`, `camel-netty4-http`, `camel-salesforce`.
// end::update_2_1[]

== WebSockets
// tag::update_2_2[]
Quarkus can be used to handling web sockets.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-undertow-websockets"
----

And web sockets classes can be used:

[source, java]
----
@ServerEndpoint("/chat/{username}")
@ApplicationScoped
public class ChatSocket {

    @OnOpen
    public void onOpen(Session session, 
                @PathParam("username") String username) {}

    @OnClose
    public void onClose(..) {}

    @OnError
    public void onError(..., Throwable throwable) {}

    @OnMessage
    public void onMessage(...) {}

}
----
// end::update_2_2[]

<<<

== OpenAPI
// tag::update_2_3[]
Quarkus can expose its API description as https://swagger.io/specification/[OpenAPI] spec and test it using https://swagger.io/tools/swagger-ui/[Swagger UI].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-openapi"
----

Then you only need to access to `/openapi` to get OpenAPI v3 spec of services.

// tag::update_3_5[]
You can update the OpenApi path by setting `quarkus.smallrye-openapi.path` property.
// end::update_3_5[]

Also, in case of starting Quarkus application in `dev` or `test` mode, Swagger UI is accessible at `/swagger-ui`.
If you want to use it in production mode you need to set `quarkus.swagger-ui.always-include` property to `true`.

You can update the Swagger UI path by setting `quarkus.swagger-ui.path` property.

[source, properties]
----
quarkus.swagger-ui.path=/my-custom-path
----
// end::update_2_3[]

== Mail Sender
// tag::update_2_5[]
You can send emails by using Quarkus Mailer extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-mailer"
----

You can inject two possible classes `io.quarkus.mailer.Mailer` for synchronous API or `io.quarkus.mailer.ReactiveMailer` for asynchronous API.

[source, java]
----
@Inject
Mailer mailer;

@Inject
ReactiveMailer reactiveMailer;
----

And then you can use them to send an email:

[source, java]
----
mailer.send(
    Mail.withText("to@acme.org", "Subject", "Body")
);

CompletionStage<Void> stage = 
    reactiveMailer.send(
        Mail.withText("to@acme.org", "Subject", "Body")
    );
----

`Mail` class contains methods to add `cc`, `bcc`, `headers`, `bounce address`, `reply to`, `attachments`, `inline attachments` and `html body`.

[source, java]
----
mailer.send(Mail.withHtml("to@acme.org", "Subject", body)
      .addInlineAttachment("quarkus.png",
            new File("quarkus.png"),
            "image/png", "<my-image@quarkus.io>"));
----

TIP: If you need deep control you can inject Vert.x mail client `@Inject  MailClient client;`

You need to configure SMTP properties to be able to send an email:

[source, properties]
----
quarkus.mailer.from=test@quarkus.io
quarkus.mailer.host=smtp.sendgrid.net
quarkus.mailer.port=465
quarkus.mailer.ssl=true
quarkus.mailer.username=....
quarkus.mailer.password=....
----

List of Mailer parameters.
`quarkus.` as a prefix is skipped in the next table.

|===	
|Parameter | Default | Description

a|`mailer.from`
|
a|Default address.

a|`mailer.mock`
a|false in `prod`, true in `dev` and `test`.
|Emails not sent, just printed and stored in a `MockMailbox` bean.

a|`mailer.bounce-address`
|
|Default address.

a|`mailer.host`
a|_mandatory_
|SMTP host.

a|`mailer.port`
|25
|SMTP port.

a|`mailer.username`
|
|The username.

a|`mailer.password`
|
|The password.

a|`mailer.ssl`
a|`false`
|Enables SSL.

a|`mailer.trust-all`
|false
|Trust all certificates.

a|`mailer.max-pool-size`
|10
|Maximum number of open connections .

a|`mailer.own-host-name`
|
a|Hostname for `HELO/EHLO` and `Message-ID`

a|`mailer.keep-alive`
a|`true`
|Connection pool enabled.

a|`mailer.disable-esmtp`
a|`false`
|Disable ESMTP.

a|`mailer.start-tls`
a|`OPTIONAL`
a|TLS security mode. `NONE`, `OPTIONAL`, `REQUIRED`.

a|`mailer.login`
a|`NONE`
a|Login mode. `NONE`, `OPTIONAL`, `REQUIRED`.

a|`mailer.auth-methods`
|All methods.
|Space-separated list.

a|`mailer.key-store`
|
|Path of the key store.

a|`mailer.key-store-password`
|
|Key store password.
|===

// tag::update_3_7[]

*Testing*

If `quarkus.mailer.mock` is set to `true`, which is the default value in `dev` and `test` mode, you can inject `MockMailbox` to get the sent messages.

[source, java]
----
@Inject
MockMailbox mailbox;

@BeforeEach
void init() {
    mailbox.clear();
}

List<Mail> sent = mailbox
                    .getMessagesSentTo("to@acme.org");
----
// end::update_3_7[]

// end::update_2_5[]

<<<

== Scheduled Tasks
// tag::update_3_2[]
You can schedule periodic tasks with Quarkus.

[source, java]
----
@ApplicationScoped
public class CounterBean {

    @Scheduled(every="10s")
    void increment() {}

    @Scheduled(cron="0 15 10 * * ?")
    void morningTask() {}
}
----

`every` and `cron` parameters can be surrounded with `{}` and the value is used as config property to get the value. 

[source java]
----
@Scheduled(cron = "{morning.check.cron.expr}")
void morningTask() {}
----

And configure the property into `application.properties`:

[source, properties]
----
morning.check.cron.expr=0 15 10 * * ?
----
// end::update_3_2[]

== Kogito
// tag::update_3_9[]
Quarkus integrates with http://www.kiegroup.org/[Kogito], a next-generation business automation toolkit from Drools and jBPM projects for adding business automation capabilities.

To start using it you only need to add the next extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="kogito"
----

// end::update_3_9[]