== Persistence

Quarkus works with JPA(Hibernate) as persistence solution.
But also provides an https://en.wikipedia.org/wiki/Active_record_pattern[Active Record pattern] implementation under Panache project.

To use database access you need to add Quarkus JDBC drivers instead of the original ones.
At this time `H2`, `MariaDB`, `MSSQL` and `PostgreSQL` drivers are supported.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-hibernate-orm-panache, 
                io.quarkus:quarkus-jdbc-mariadb"
----

[source, java]
----
@Entity
public class Developer extends PanacheEntity {

    // id field is implicit

    public String name;
}
----

And configuration in `src/main/resources/application.properties`:

[source, properties]
----
quarkus.datasource.url=jdbc:mariadb://localhost:3306/mydb
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.datasource.username=developer
quarkus.datasource.password=developer
quarkus.hibernate-orm.database.generation=update
----

Database operations:

[source, java]
----
// Insert
Developer developer = new Developer();
developer.name = "Alex";
developer.persist();

// Find All
Developer.findAll().list();

// Find By Query
Developer.find("name", "Alex").firstResult();

// Delete
Developer developer = new Developer();
developer.id = 1;
developer.delete();

// Delete By Query
long numberOfDeleted = Developer.delete("name", "Alex");
----

<<<

Remember to annotate methods with `@Transactional` annotation to make changes persisted in the database.

If queries start with the keyword `from` then they are treated as _HQL_ query, if not then next short form is supported:

* `order by` which expands to `from EntityName order by ...`
* `<columnName>` which expands to `from EntityName where <columnName>=?`
* `<query>` which is expanded to `from EntityName where <query>`

*Static Methods*

|===	
| Field | Parameters | Return

a| `findById`
a| `Object`
a| Returns object or null if not found.

a| `find`
a| `String`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| Lists of entities meeting given query with parameters set.

a| `find`
a| `String`, `Sort`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| Lists of entities meeting given query with parameters set sorted by `Sort` attribute/s.

a| `findAll`
a| 
a| Finds all entities.

a| `findAll`
a| `Sort`
a| Finds all entities sorted by `Sort` attribute/s.

a| `stream`
a| `String`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| `java.util.stream.Stream` of entities meeting given query with parameters set.

a| `stream`
a| `String`, `Sort`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| `java.util.stream.Stream` of entities meeting given query with parameters set sorted by `Sort` attribute/s.

a| `streamAll`
a| 
a| `java.util.stream.Stream` of all entities.

a| `streamAll`
a| `Sort`
a| `java.util.stream.Stream` of all entities sorted by `Sort` attribute/s.

a| `count`
a| 
a| `Number of entities.

a| `count`
a| `String`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| Number of entities meeting given query with parameters set.

a| `deleteAll`
a| 
a| Number of deleted entities.

a| `delete`
a| `String`, [`Object...`, `Map<String, Object>`, `Parameters`]
a| Number of deleted entities meeting given query with parameters set.

a| `persist`
a| [`Iterable`, `Steram`, `Object...`]
a| 
|===

// tag::update_2_10[]
If entities are defined in external JAR, you need to enable in these projects the `Jandex` plugin in project.

[source, xml]
----
<plugin>
    <groupId>org.jboss.jandex</groupId>
    <artifactId>jandex-maven-plugin</artifactId>
    <version>1.0.3</version>
    <executions>
        <execution>
            <id>make-index</id>
            <goals>
                <goal>jandex</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.1.1.Final</version>
        </dependency>
    </dependencies>
</plugin>
----
// end::update_2_10[]

*DAO pattern*

// tag::update_2_12[]
Panache also supports _DAO_ pattern by providing `PanacheRepository<TYPE>` interface.

[source, java]
----
@ApplicationScoped
public class DeveloperRepository 
    implements PanacheRepository<Person> {
   public Person findByName(String name){
     return find("name", name).firstResult();
   }
}
----
// end::update_2_12[]

== Flyway
// tag::update_1_7[]
Quarkus integrates with https://flywaydb.org/[Flyway] to help you on database schema migrations.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-flyway"
----

Then place migration files to the migrations folder (`classpath:db/migration`).

You can inject `org.flywaydb.core.Flyway` to programmatically execute the migration.

[source, java]
----
@Inject
Flyway flyway;

flyway.migrate();
----

Or can be automatically executed by setting `migrate-at-start` property to `true`.

[source, properties]
----
quarkus.flyway.migrate-at-start=true
----

List of Flyway parameters.

`quarkus.` as prefix is skipped in the next table.

|===	
|Parameter | Default | Description

a|`flyway.migrate-at-start`
a|`false`
|Flyway migration automatically.

a|`flyway.locations`
a|`classpath:db/migration`
|CSV locations to scan recursively for migrations. Supported prefixes `classpath` and `filesystem`.

a|`flyway.connect-retries`
a|0
|The maximum number of retries when attempting to connect.

a|`flyway.schemas`
a|none
|CSV case-sensitive list of schemas managed.

a|`flyway.table`
a|`flyway_schema_history`
|The name of Flyway’s schema history table.

a|`flyway.sql-migration-prefix`
a|`V`
|Prefix for versioned SQL migrations. 

a|`flyway.repeatable-sql-migration-prefix`
a|`R`
|Prefix for repeatable SQL migrations.
|===
// end::update_1_7[]