name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Node 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev ghostscript poppler-utils
    - name: Install dependencies
      run: npm ci
    - name: Lint and test
      run: |
        npm run lint
        npm t
    - name: Setup Docker
      # taken from https://github.com/docker/github-actions/blob/0f18e2abad9a4ac2963d2516246787375b5ec917/Dockerfile#L32
      run: curl -fL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.4.tgz | tar xzO docker/docker > docker && sudo mv -f docker /usr/bin/docker && sudo chmod +x /usr/bin/docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build container image
      run: make packageLocalDocker
    - name: Smoke test
      run: make testDocker

  build:
    needs: check
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac-arm64
            artifact: mac-arm64-binary
          - os: ubuntu-latest
            platform: linux-x64
            artifact: linux-x64-binary
          - os: ubuntu-24.04-arm
            platform: linux-arm64
            artifact: linux-arm64-binary
          - os: windows-latest
            platform: win-x64
            artifact: win-x64-binary
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Node 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Build binary
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: build/asciidoctor-web-pdf-${{ matrix.platform }}.zip
